#!/bin/bash
if [ $# -eq 0 ]; then
  echo "Usage: $0 create|update <SSHKEY> <DNSNAME> <DNSDOMAIN>"
  echo "e.g. $0 create default registry example.com"
  exit 1
else
  # We use the DNS domain in the CloudFormation
  # stack name  (no dashes in stack names).
  export AWS_DEFAULT_PROFILE=$3-`echo $4 | sed -e 's/\./\-/g'`

  # Sets your external IP for the load-balancer security group
  #IPADDRESS=`wget -qO- http://ipecho.net/plain ; echo -n`
  IPADDRESS=`curl -s http://whatismijnip.nl |cut -d " " -f 5`
  
  # Configures the aws-cli, requires an access key is and secret
  aws configure --profile $AWS_DEFAULT_PROFILE

  # Creates a CloudFormation stack for the ECS cluster
  aws cloudformation $1-stack \
    --stack-name $AWS_DEFAULT_PROFILE \
    --template-body file://cloudformation.json \
    --capabilities CAPABILITY_IAM \
    --parameters ParameterKey=SSHLocation,ParameterValue="$IPADDRESS/32" \
ParameterKey=KeyName,ParameterValue="$2" \
ParameterKey=DNSName,ParameterValue="$3" \
ParameterKey=DNSDomain,ParameterValue="$4"
fi
